Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2,

> fib = 1 : 2 : zipWith (+) fib (tail fib)

The first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

> first10 = take 10 fib

Find the sum of all the even-valued terms in the sequence which do not exceed
one million.

> answer = sum . filter even . takeWhile (<1000000) $ fib

> main = do print first10
>           print answer
